# Generated by Django 6.0.3 on 2026-03-17 15:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200, verbose_name='İngilizce')),
                ('turkish', models.CharField(max_length=200, verbose_name='Türkçe')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Örnek Cümle')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('repetitions', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=1)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(choices=[('new', 'Yeni'), ('learning', 'Öğreniliyor'), ('review', 'Tekrar'), ('mastered', 'Öğrenildi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('interval_after', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='flashcards.word')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
