# Generated by Django 6.0.3 on 2026-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.CharField(blank=True, help_text='Virgülle ayır: transient, fleeting, momentary', max_length=400, verbose_name='Eş Anlamlılar'),
        ),
    ]
